version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network
    restart: unless-stopped

  app:
    build: ./app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=your_database
    volumes:
      - ./app/logs:/app/logs
    depends_on:
      - db
    deploy:
      replicas: 3
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:
  db_logs:
  app_logs:

networks:
  app_network:
    driver: bridge